### ISSUE TITLE
Issue on page /logik.html

### ISSUE THREAD

**Issue by Line99167** [georgmerz/gdma#1]
In dem Beispiel wird erklärt dass z von x abhängig sein darf weil der Existenzquantor(y) nach dem Allquantor(x) kommt. Müsste das aber nicht der Existenzquantor(z) sein statt (y)?
![Issue](https://github.com/user-attachments/assets/cedd34b6-1276-4c83-9bcc-453098bbc4eb)

**Comment by georgmerz** [comment]
Korrekt. Danke für den Hinweis
